from tkinter import *
window=Tk()
window.geometry("300x200")
window.title("Registration form")
#Labels
t=Label(window,text="Form")
t.grid(row=0,column=1)
a=Label(window,text="Name")
a.grid(row=1,column=0)
b=Label(window,text="Course")
b.grid(row=2,column=0)
c=Label(window,text="Semester")
c.grid(row=3,column=0)
d=Label(window,text="Form no.")
d.grid(row=4,column=0)
e=Label(window,text="Contact no.")
e.grid(row=5,column=0)
f=Label(window,text="Email id")
f.grid(row=6,column=0)
g=Label(window,text="address")
g.grid(row=7,column=0)
a.configure(bg="light green")
b.configure(bg="light green")
c.configure(bg="light green")
d.configure(bg="light green")
e.configure(bg="light green")
f.configure(bg="light green")
g.configure(bg="light green")
t.configure(bg="light green")
#Entries
name=Entry(window,width=25)
name.grid(row=1,column=1)
course=Entry(window,width=25)
course.grid(row=2,column=1)
semester=Entry(window,width=25)
semester.grid(row=3,column=1)
form=Entry(window,width=25)
form.grid(row=4,column=1)
contact=Entry(window,width=25)
contact.grid(row=5,column=1)
email=Entry(window,width=25)
email.grid(row=6,column=1)
address=Entry(window,width=25)
address.grid(row=7,column=1)
def submit():
 print(name.get())
 print(course.get())
 print(semester.get())
 print(form.get())
 print(contact.get())
 print(email.get())
 print(address.get())
 name.delete(0,END)
 course.delete(0, END)
 semester.delete(0, END)
 form.delete(0, END)
 contact.delete(0, END)
 email.delete(0, END)
 address.delete(0, END)
Button(window,text="Submit",bg="red",command=submit).grid(row=8,column=1)
window.configure(bg='light green')
window.mainloop()